name: Build

permissions:
  contents: read

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build

    strategy:
      fail-fast: true
      matrix:
        include:
          - target: windows
            os: windows-latest
          - target: linux
            os: ubuntu-latest
          - target: macos
            os: macos-latest
          - target: jvm
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '16'

      - uses: gradle/actions/setup-gradle@v3

      - name: Publish to Maven Central
        run: |
          if [ ${{ matrix.target }} == jvm ]; then
            ./gradlew compileKotlinJvm
          else
            case ${{ matrix.os }} in
              windows-latest)
              ./gradlew compileKotlinMingwX64
              ;;
              ubuntu-latest)
              ./gradlew compileKotlinLinuxX64
              ;;
              macos-latest)
              ./gradlew compileKotlinMacosX64
              ;;
            esac
          fi
