name: Build

permissions:
  contents: read

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '16'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Cache Konan
        id: cache-kotlin-konan
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan/**/*
          key: kotlin-konan-

      - name: Build project
        run: ./gradlew compileKotlinJvm compileKotlinMingwX64 compileKotlinLinuxX64 compileKotlinLinuxArm64 compileKotlinMacosX64 compileKotlinMacosArm64 --build-cache --parallel --no-daemon
