name: Build

permissions:
  contents: read

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '16'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build project
        run: ./gradlew compileKotlinJvm compileKotlinMingwX64 compileKotlinLinuxX64 compileKotlinLinuxArm64 compileKotlinMacosX64 compileKotlinMacosArmX64
